travis:
  secure:
    BINSTAR_TOKEN: KGUGTyqbStzAbRspB+ZI2Qt1s4mAuyv/eeIvlcCOEAzM8BpKqy/jAZC8M2WvAgsXywvA1j/fIZu+6leHYURDM+rChW16fNOc/lz8JzU+CDvrK3LG9N1dYRs1c38D9Iybrb2Fmv2gudLvPpdUzraYNj1Ga4j1XKWKniqVGSYiUkJTV1OBkmC6zjEnZGMZDBNvCA6i9LD2DsXDbl2AtBYfVuJM8y2ux+vPdFbmUHFUFaMQQ1bjCr0Yj92/I/+34S42E7M/UOVJBPe9FvyswLamQwpWmtk01IvHnCNNuxgFpmAcERlVD532KYsSiyEYw+74nUB6VIvz7O0bOswzJbrQoSeZxny/+VXdf60N6yU1/+r3XMS7TGgsTAKD59gSPsVL6+QUm5IyiLfZrQ7/88EaA5VtBMZRhSBiyFG+GESlMNkXmYzvxezUvuOZQQSIVwTglP+8scPRcdKRJXTYYUvAKnmNexfYIy/YcaLWNkfoOMMma70bOykY6pyTxDwPLvGUUbjNPR6ZD+xgFwB2yOZlVfTaFPmv5kWi6pbEYCDmFyVtCAU3W0IagDwchnUryU+wr3n+H8RtPQRn4QiTwkfoku6E0cN92QgH7bY8yl+FtjxtWyStKbKKYmDNaIKZMWhq7rznQM7AAWE68a+j8DRGVgyxDiOmMgg5SBh+DbRIC0Q=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
